language: perl6
sudo: false
os:
  - linux
perl6:
  - latest
  - '2019.03'
install:
  - rakudobrew build zef
  - git clone https://github.com/p6-pdf/PDF-Class-p6.git
  - (cd PDF-Class-p6/ && zef install .)
  - zef --depsonly install .
script:
  - prove -ve "perl6 -I."
  - zef install .
